spring.application.name=admin-service
server.port=8083
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/shipfast_admin}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,https://shipfast-hazel.vercel.app,https://shipfast-new.onrender.com}

