server.port=8081

spring.application.name=Shipment-service

spring.data.mongodb.uri=mongodb://localhost:27017/shipfast_new
operations.service.url=http://localhost:8082

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lingesw0561@gmail.com
spring.mail.password=pbxmygjsskqktcfd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
