spring.application.name=Authenticate
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/shipfastAuth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Abcdefg89@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=c2hpcGZhc3Qtc2VjcmV0LWtleS1zaGlwZmFzdC1rZXk=
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lingesw0561@gmail.com
spring.mail.password=pbxmygjsskqktcfd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

eureka.client.enabled=false
operations.service.url=http://localhost:8082/api/operations
