spring.application.name=reporting-service
server.port=8087
spring.data.mongodb.uri=${MONGO_URI}
shipment.service.url=${SHIPMENT_SERVICE_URL:}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,https://shipfast-new.onrender.com}
