spring.application.name=operations-service
server.port=8082
spring.data.mongodb.uri=${MONGO_URI}
shipment.service.url=${SHIPMENT_SERVICE_URL:}

spring.main.lazy-initialization=true
spring.main.banner-mode=off

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

server.servlet.context-path=/api