server.port=8086
spring.application.name=COMMUNICATION-SERVICE

spring.data.mongodb.uri=${MONGO_URI}

spring.web.error.include-message=never
spring.main.lazy-initialization=true
spring.main.banner-mode=off

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.server.port=
