server.port=${PORT:8086}
spring.application.name=COMMUNICATION-SERVICE

spring.data.mongodb.uri=${MONGO_URI}

spring.web.error.include-message=never
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,https://shipfast-hazel.vercel.app,https://shipfast-new.onrender.com}
spring.main.lazy-initialization=true
spring.main.banner-mode=off
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.server.port=
