server.port=8086
spring.application.name=COMMUNICATION-SERVICE

spring.data.mongodb.uri=${MONGO_URI}

spring.web.error.include-message=never
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,https://shipfast-new.onrender.com}
